require('tecabel.plugins')
require('tecabel.base')
require('tecabel.maps')
require('tecabel.catppuccin')
-- require('tecabel.gruvbox')
require('tecabel.lsp-config')
require('tecabel.fidget')
require('tecabel.telescope')
-- require('tecabel.treesitter')
require('tecabel.bufferline')
