require('tecabel.plugins')
require('tecabel.base')
require('tecabel.maps')
require('tecabel.gruvbox')
require('impatient')
require('tecabel.lsp-config')
require('tecabel.null')
require('tecabel.telescope')
require('tecabel.treesitter')
require('tecabel.bufferline')
vim.cmd([[ colorscheme gruvbox ]])
-- require('tecabel.treesitter-context')
