require('tecabel.plugins')
require('tecabel.base')
require('tecabel.maps')
require('tecabel.catppuccin')
-- require('tecabel.gruvbox')
require('impatient')
require('tecabel.lsp-config')
require('tecabel.telescope')
require('tecabel.treesitter')
require('tecabel.bufferline')
